# Cấu hình Server
server.port=5000

# Bật debug log cho Web và Security
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=DEBUG

# Cấu hình Cơ sở dữ liệu (PostgreSQL trên Aiven)
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Các thuộc tính JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Cài đặt tải lên tệp tin (File Upload)
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
spring.servlet.multipart.enabled=true

# Cấu hình Bảo mật (Security)
jwt.secret=${JWT_SECRET}
client.url=${CLIENT_URL}

# Thông tin xác thực MoMo Sandbox
momo.partner-code=${MOMO_PARTNER_CODE}
momo.access-key=${MOMO_ACCESS_KEY}
momo.secret-key=${MOMO_SECRET_KEY}
momo.api-url=${MOMO_API_URL}

# Thông tin xác thực Ngân hàng VietQR
bank.id=${BANK_ID}
bank.account-no=${BANK_ACCOUNT_NO}
bank.account-name=${BANK_ACCOUNT_NAME}

# Cấu hình Cloudinary
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}
cloudinary.folder=${CLOUDINARY_FOLDER}

# Thông tin xác thực Google OAuth
google.client-id=${GOOGLE_CLIENT_ID}

# Model AI Hugging Face Space tùy chỉnh
hf.token=${HF_TOKEN}
hf.space-url=${HF_SPACE_URL}
ai.detection-threshold=${AI_DETECTION_THRESHOLD}

# Cấu hình HikariCP:
spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=20000
